name: Release
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create DMG
        run: |
          brew install create-dmg
          mkdir -p /tmp/SplitWire
          cp -r launchd scripts README.md /tmp/SplitWire/
          create-dmg --volname "SplitWire" --window-size 600 400 /tmp/SplitWire.dmg /tmp/SplitWire
      - name: Create PKG
        run: |
          pkgbuild --root /tmp/SplitWire --identifier com.consolaktif.splitwire --version ${GITHUB_REF_NAME} /tmp/SplitWire.pkg
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/SplitWire.dmg
            /tmp/SplitWire.pkg
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
